source 'https://rubygems.org'

gem 'cucumber'
gem 'capybara'
gem 'site_prism'
gem 'selenium-webdriver', '2.51.0'
gem 'require_all', '1.2.1'
gem 'test-unit', '2.5.5'
gem 'rake', '10.2.0'
gem 'spreadsheet', '0.8.5'
gem 'rumouse'
gem 'pdf-reader'
gem 'ffi', '1.9.10'
gem 'colorize'
gem 'rspec'