source 'https://rubygems.org'

#gem 'site_prism', '2.4'
#gem 'cucumber'
#gem 'selenium-webdriver'
#gem 'minitest'
#gem 'colorize'
#gem 'capybara', '2.5.0'


gem 'cucumber', '2.3.2'
gem 'capybara', '2.5.0'
gem 'site_prism', '2.4'
gem 'selenium-webdriver', '2.51.0'
gem 'require_all', '1.2.1'
gem 'test-unit', '2.5.5'
gem 'rake', '10.2.0'
gem 'spreadsheet', '0.8.5'
gem 'rumouse'
gem 'pdf-reader'
gem 'ffi', '1.9.10'
gem 'colorize'